# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'loops', github: 'tonybyrne/loops'
gem 'activesupport'
gem 'redis-queue'

group :development do
  gem 'byebug'
  gem 'pry'
end
