# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

gem 'activesupport'
gem 'loops', github:'tonybyrne/loops'

group :development, :test do
  gem 'colourer'
  gem 'rspec'
  gem 'guard-rspec'
  gem 'vcr'
  gem 'webmock'
  gem 'awesome_print'
end
