# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y vim htop curl git nodejs
    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 
    curl -sSL https://get.rvm.io | bash -s stable
    adduser vagrant rvm && \
    . /usr/local/rvm/scripts/rvm && rvm install ruby-2.3.3 && rvm use ruby-2.3.3 && gem install bundler && cd /vagrant && \
    bundle install && gem install foreman
  SHELL
end
